# Generated by Django 5.0.1 on 2024-01-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_custome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custome',
            new_name='Customer',
        ),
    ]
